scripts: script
tests: test
default: help
url: git://github.com/eitherlands/manage.git
maintainer: "Mark Milstein <mark+github@eitherlands.com> (@epiloque)"
versions:
  legacy: 0.1.4
  stable: 0.1.5
dependencies:
  - bash
  - awk
  - sed
  - tr
  - head
env:
  HELLO: "Hello World!"
