scripts: script
tests: test
default: help
dependencies:
  - bash
  - awk
  - sed
  - tr
  - head
env:
  HELLO: "Hello World!"
  MANAGEURL: "git://github.com/eitherlands/manage"
  MANAGEMAINTAINER: "Mark Milstein <mark+github@eitherlands.com> (@epiloque)"
