# Relative path to the script directory
scripts: script

# Default script to execute
default: help

# Check for the following dependencies in PATH
dependencies:
  - bash
  - awk
  - sed
  - tr
  - head

# Environment variables
env:
  HELLO: "Hello World!"

#
# script: test
#
# Relative path to the test directory
test:
  tests: test

#
# script: versions
#

versions:
  url: https://github.com/eitherlands/manage.git
  maintainer: "Mark Milstein <mark+github@eitherlands.com> (@epiloque)"
  key: https://epiloque.github.io/epiloque.pub
  verify: true
  versions:
    legacy: 0.1.6
    stable: 0.1.7

#
# script: assemble
#

assemble:
  internal: true
  versions:
    - 0.1.7
    - 0.1.6
