language: bash
sudo: 9000
script:
- bin/manage assemble
env:
  global:
    secure: Gp9OiPlJZvYkOgMvj2pNgELof4Eof1yi+80xUomDG2Rule8FGsszx2FddUpr32uW/cHReEudxRgjvOYyGz2lKCzRjlvRBOn50SwndCmPgfZ3fCzOnTc+B/Mg4eioa9SmIqdaSZlGVwWNdbxLNCHluBFYpMLYKQzNJhS/89mv+xVx8MUIGboxB2blZ+CwdLH+fDTqJWmApzHa+VgLxiLSBdXrgFaptxWbsQURewC1AlglwrA32d8foRtDHXheY/0dzTZPRg7QRWBlRQrs3AM6DO/42lLyi3NnVeURgKtOOhvT9Ao+b96QrkF/JisPsNjti7nU5TQLvqNA5kfNi52IT33GJl1SgJfykBH2rLFkje8JRxQqhX05xw98LxgJmYvEKzX/aM3n9O5AmLGz3SDHPlv2/yIMnfgeE1YXBmPsaXmyMjXMahnjRbrVhGfDT6CQdJT8CObU1lgZROShUxwCob2u0T7tW64dF4yxoKWC85Ycq0GKU21O7yqCd5I81eS8qFyulbJ0FHfFXH0gj2paJvZnLosdoAMZXgmWCTb17WIYoT/B/Q41vhY0pvcQ+gr7atmuLYYRpeZxU0dnw6bpQZxYzV1undReFiKtElzvEZf56aCsvzxyCC2NoqIH6eNof1Qp3CmwjyhekMhEvadOFFhcsE/xC3PNNyff3FtqPM4=
notifications:
  email:
    on_success: never
