sudo: required
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
script:
  - ./manage trust-escapace
  - ./manage ci

language: bash
matrix:
  include:
    - os: linux
      services: docker
      language: bash
      env: TEST_SUITE=lint
    - os: linux
      services: docker
      language: bash
      env: TEST_SUITE=centos
    # - os: osx
    #   language: bash
    #   env: TEST_SUITE=osx
    #   before_script:
    #     - brew update
    #     - brew install bash
    #     - brew install gnu-sed
    #     - brew upgrade coreutils
    #     - brew upgrade gnupg
    #     - brew upgrade git
    #     - /usr/local/bin/bash --version
branches:
  only:
    - next
    - staging
    - development
    - /^v?\d+\.\d+\.\d+$/
    - /^\d+\.\d+\.\d+$/
    - /^new-.*$/
    - /^feat-.*$/
    - /^add-.*$/
    - /^change-.*$/
    - /^breaking-.*$/
    - /^deprecate-.*$/
    - /^remove-.*$/
    - /^fix-.*$/
    - /^sec-.*$/
    - /^security-.*$/
    - /^perf-.*$/
    - /^performance-.*$/
    - /^test-.*$/
    - /^tests-.*$/
notifications:
  email:
    on_success: change
    on_failure: always
