sudo: required
before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
language: bash
matrix:
  include:
    - os: linux
      services: docker
      language: bash
      env: TEST_SUITE=lint
      script:
        - gpg --keyserver ha.pool.sks-keyservers.net --recv-key 13F26F82E955B8B8CE469054F29CCEBC83FD4525
        - ./bin/manage ci
    - os: linux
      services: docker
      language: bash
      env: TEST_SUITE=fedora
      script:
        - gpg --keyserver ha.pool.sks-keyservers.net --recv-key 13F26F82E955B8B8CE469054F29CCEBC83FD4525
        - ./bin/manage ci
    - os: linux
      services: docker
      language: bash
      env: TEST_SUITE=alpine
      script:
        - gpg --keyserver ha.pool.sks-keyservers.net --recv-key 13F26F82E955B8B8CE469054F29CCEBC83FD4525
        - ./bin/manage ci
    # - os: osx
    #   language: bash
    #   env: TEST_SUITE=osx
    #   script:
    #     - brew update
    #     - brew install bash
    #     - brew install gnu-sed
    #     - brew upgrade coreutils
    #     - brew upgrade gnupg
    #     - brew upgrade git
    #     - gpg --keyserver ha.pool.sks-keyservers.net --recv-key 13F26F82E955B8B8CE469054F29CCEBC83FD4525
    #     - /usr/local/bin/bash --version
    #     - /usr/local/bin/bash bin/manage ci
branches:
  only:
    - staging
    - development
    - next
    - /^v?\d+\.\d+\.\d+$/
    - /^\d+\.\d+\.\d+$/
    - /^new-.*$/
    - /^feat-.*$/
    - /^add-.*$/
    - /^change-.*$/
    - /^breaking-.*$/
    - /^deprecate-.*$/
    - /^remove-.*$/
    - /^fix-.*$/
    - /^sec-.*$/
    - /^security-.*$/
    - /^perf-.*$/
    - /^performance-.*$/
    - /^test-.*$/
    - /^tests-.*$/
notifications:
  email:
    on_success: change
    on_failure: always
