language: bash
matrix:
  include:
    - os: linux
      services: docker
      language: bash
      env: TEST_SUITE=lint
      script:
        - gpg --keyserver pgp.mit.edu --recv-key 0x671C330913823C5B
        - ./bin/manage ci
    - os: linux
      services: docker
      language: bash
      env: TEST_SUITE=fedora
      script:
        - gpg --keyserver pgp.mit.edu --recv-key 0x671C330913823C5B
        - ./bin/manage ci
    - os: linux
      services: docker
      language: bash
      env: TEST_SUITE=alpine
      script:
        - gpg --keyserver pgp.mit.edu --recv-key 0x671C330913823C5B
        - ./bin/manage ci
    - os: osx
      language: bash
      env: TEST_SUITE=osx
      script:
        - brew update
        - brew install bash
        - brew install gnu-sed
        - brew upgrade coreutils
        - brew upgrade gnupg
        - brew upgrade git
        - gpg --keyserver pgp.mit.edu --recv-key 0x671C330913823C5B
        - /usr/local/bin/bash --version
        - /usr/local/bin/bash bin/manage ci
branches:
  only:
    - staging
    - development
    - next
    - /^v?\d+\.\d+\.\d+$/
    - /^\d+\.\d+\.\d+$/
    - /^new-.*$/
    - /^feat-.*$/
    - /^add-.*$/
    - /^change-.*$/
    - /^breaking-.*$/
    - /^deprecate-.*$/
    - /^remove-.*$/
    - /^fix-.*$/
    - /^sec-.*$/
    - /^security-.*$/
    - /^perf-.*$/
    - /^performance-.*$/
    - /^test-.*$/
    - /^tests-.*$/
notifications:
  email:
    on_success: change
    on_failure: always
