language: bash
services: docker
script:
- bin/manage lint
branches:
  only:
    - master
    - staging
    - development
    - /^v?\d+\.\d+\.\d+$/
    - /^\d+\.\d+\.\d+$/
    - /^new-.*$/
    - /^feat-.*$/
    - /^add-.*$/
    - /^change-.*$/
    - /^breaking-.*$/
    - /^deprecate-.*$/
    - /^remove-.*$/
    - /^fix-.*$/
    - /^sec-.*$/
    - /^security-.*$/
    - /^perf-.*$/
    - /^performance-.*$/
    - /^test-.*$/
    - /^tests-.*$/
language: bash
addons:
  apt:
    sources:
    - debian-sid
    packages:
    - shellcheck
env:
  global:
  - MANAGE_BUILD_DEBUG: true
  - secure: kU2Q/S3UrusoZmQx09fpRbtW+gX6ixwbItHv6jj87xGcGIJjt4TxPdNLDGfTEcmn6kaEvINJryRWpt90m5YFdmYzkxhFXoSVkI2tiyd1Gzs4y81ew/ecq60aHE16zZxWfTK0yLKfQNXtPQ94VFxh0Q667YG0tFoNswbICQWiKC8t+0+y4Qc8Av9S6clnQyTc8vl8tuqU90WsViMAVyEN6JqrS8gL9iQOXYetVUSIRX2lsA98QFWv5JKwHfxWBlRX/P+O1FVZcqXVFXuDV2/g1dH2iBBd3u+gZ+btsPckFzE8TigXgfWWuvjX4/olodf8T5eoGRN8N8HMBi0qaXfMwiPEGlHXFNg+3HwXcEkloiv29gFpssUtmRaFfqtefN3ocSHp8QGxwbmHxCMTUTa0dyg0CF2ADjFjr+URc4Vbl3TznHB2WkCqimh+9AFK+GkucGjLv4L/zYKFguGJ53BEshAKrpHJEJGi9mNvx6cCEW+KyTq4zWy7n/U0LnZRRiZciSjDCFupFub56VtS8dKeC3ycrNwlw1zveo73haVqEnglHlq63waMPzpm+VjPzTUus4HV7rALp/Vo4hGKS7QXr/1Ouo7AiaLgqusVQXlThEt0usChiNYrG9wmVTRzSY1VHsh16Vnx19XKLD2JZzCoFNoFu7BR05PGP9YZ/l6Y94Q=
notifications:
  email:
    on_success: change
    on_failure: always
