language: bash
before_script: "./manage trust-escapace"
script: "./manage test"
branches:
  only:
    - master
notifications:
  email: false
deploy:
  provider: releases
  api_key:
    secure: Uimq2LTRoXWzUKr5SHTR6qVfoItGOM/QEdwuMaSaS/Os8B7EJK12/XHPLZqb58LDnB1X0Io+qd/gKTl/4cNVmQObJNiq2G9ipiONW98aod5MkBw96cckAK7pSJp/mONgFTG0+yZkysWwJZaK+sCKIJVF7WDDqzXSg9L8MK8YekXH80tgUJYzXQGWL72JwUS5N92ooUvxon3vEcb9sAGt4z63a2yIi5yvjLu80D4wa1KWo/4nr1rBI59ZtVkzX4ZUPPddXQmU/5NoywP3ZKQ+fV88S/Xc6fOIX90Tn0T8SEsG9QqQHNzKPZNtAOB2StTFDHAeMYTcOzOnbayU1zHTuX2+wI5WnotVomzezV70kRYkAmdNG2YyoHqTsgSq1moV/JvYp7D96X15CNUAz5lQ9CG4kNy5g/RSXaMI5oSWWL0hG939aKP3kxWj9JzKZg6L74xjg2pdnVrpEdxLtpVCAaolDV/K+q6Kf9kauIsfqWZs7JboSHd8mgxL/J3XOFl3S3ZBe3WDmae6DId2gGIXrZtMgi+E+eNqiWP+c1UXDAbWL+pGWe8mVGfN8yJdmEk/Jgc5PsSODbbeJDY3jev+3yHLvgOj/xQqyeKCn5psE+Ws9L1qsleXemsGiFR8B3pRBrAYFI2PZ1kJUb1XfGV7EpofONQpZ54zSJwF2Vnl6LA=
  file: manage
  on:
    repo: escapace/manage
    branch: master
