on:
  push:
    branches:
    - '*'
    - '!master'
    tags:
    - 'v*'
name: Pipeline
jobs:
  test-linux:
    name: "Linux Test"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        suite: [lint, centos, alpine]
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
    - name: manage ci
      run: |
        ./manage trust-escapace
        ./manage ci
      env:
        TEST_SUITE: ${{ matrix.suite }}
  test-macOS:
    name: "macOS Test"
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2.0.0
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: manage ci
      run: |
        brew install bash gnu-sed gnupg
        ./manage trust-escapace
        ./manage ci
      env:
        TEST_SUITE: osx
  docker:
    name: "Docker build and push"
    runs-on: ubuntu-latest
    needs: [test-macOS, test-linux]
    steps:
    - uses: actions/checkout@v2.0.0
      if: contains(github.ref, 'tags/v')
    - name: Checkout submodules
      if: contains(github.ref, 'tags/v')
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Docker Login
      if: contains(github.ref, 'tags/v')
      uses: actions/docker/login@fe7ed3ce992160973df86480b83a2f8ed581cd50
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    - name: Docker Build
      if: contains(github.ref, 'tags/v')
      uses: actions/docker/cli@fe7ed3ce992160973df86480b83a2f8ed581cd50
      with:
        args: build -t escapace/manage:latest -t escapace/manage:${GITHUB_REF:11} .
    - name: Docker Push Latest
      if: contains(github.ref, 'tags/v')
      uses: actions/docker/cli@fe7ed3ce992160973df86480b83a2f8ed581cd50
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      with:
        args: push escapace/manage:latest
    - name: Docker Push Tag
      if: contains(github.ref, 'tags/v')
      uses: actions/docker/cli@fe7ed3ce992160973df86480b83a2f8ed581cd50
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      with:
        args: push escapace/manage:${GITHUB_REF:11}
  release:
    name: "Github Release"
    runs-on: ubuntu-latest
    needs: [test-macOS, test-linux]
    steps:
    - uses: actions/checkout@v2.0.0
      if: contains(github.ref, 'tags/v')
    - name: Checkout submodules
      if: contains(github.ref, 'tags/v')
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: release
      if: contains(github.ref, 'tags/v')
      run: |
        mkdir ~/bin
        wget -qO- https://github.com/github/hub/releases/download/v2.12.3/hub-linux-amd64-2.12.3.tgz | tar xvz -C ~/bin --strip=2 --wildcards --no-anchored 'hub*/bin/hub'
        ~/bin/hub release create -a manage -m "manage ${GITHUB_REF:11}" -t master v${GITHUB_REF:11}
      env:
        GITHUB_USER: escapace
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
